server:
  port: 9999
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: loclahost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: coches-service
          uri: lb://coches-service
          predicates:
            - Path=/coche/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**