server:
  port: 9093
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          defauld-label: develop
          uri: https://github.com/jose-richard/demo-micro
          search-paths: config-data